<?php
namespace Magenest\Movie\Ui\Component\SalesOrder;
use Magento\Ui\Component\Listing\Columns\Column;
class OddEven extends  Column{


    public function prepareDataSource(array $dataSource)
    {
        if (isset($dataSource['data']['items'])) {

            foreach ($dataSource['data']['items'] as & $item) {
                // here we can also use the data from $item to configure some parameters of an action URL
                $html = '';
                if((int)$item['increment_id'] % 2 == 0 ){
                   $item['odd_even'] = '<span class="grid-severity-notice"> Even </span>';
               }else{
                   $item['odd_even'] = '<span class="grid-severity-critical"> Odd </span>';
               }
            }
        }
        return parent::prepareDataSource($dataSource); // TODO: Change the autogenerated stub
    }
}
