<?php
namespace Magenest\Attachments\Model\ResourceModel\Attachments;

use Magento\Framework\Model\ResourceModel\Db\Collection\AbstractCollection;

class Collection extends AbstractCollection {

    protected function _construct()
    {
        $this->_init(\Magenest\Attachments\Model\Attachments::class, \Magenest\Attachments\Model\ResourceModel\Attachments::class);
        parent::_construct(); // TODO: Change the autogenerated stub
    }
}
