<?php

namespace Magenest\JuniorEAV\Model\Product\Type;

class NewProductType extends \Magento\Catalog\Model\Product\Type\Virtual
{

    const TYPE_ID = 'newproducttype';

//    public function deleteTypeSpecificData(\Magento\Catalog\Model\Product $product)
//    {
//        parent::deleteTypeSpecificData($product); // TODO: Change the autogenerated stub
//    }

    public function hasWeight()
    {
        return parent::hasWeight(); // TODO: Change the autogenerated stub
    }
}