<?php
namespace Learning\FirstUnit\Model\ResourceModel\Subscription;

class Collection extends \Magento\Framework\Model\ResourceModel\Db\Collection\AbstractCollection
{


    public function _construct()
    {
        parent::_construct(); // TODO: Change the autogenerated stub
        $this->_init('Learning\FirstUnit\Model\Subscription', 'Learning\FirstUnit\Model\ResourceModel\Subscription');
    }
}