<?php

namespace Magenest\Movie\Ui\Component\Movie\Listing\Column;

use Magento\Framework\UrlInterface;
use Magento\Framework\View\Element\UiComponent\ContextInterface;
use Magento\Framework\View\Element\UiComponentFactory;
use Magento\Ui\Component\Listing\Columns\Column;

/**
 * Class Actions
 */
class Actions extends Column
{
    /**
     * @var UrlInterface
     */
    protected $urlBuilder;

    /**
     * Prepare Data Source
     *
     * @param ContextInterface $context
     * @param UiComponentFactory $uiComponentFactory
     * @param UrlInterface $url
     * @param array $components
     * @param array $data
     */

    public function __construct(ContextInterface $context, UiComponentFactory $uiComponentFactory, UrlInterface $url, array $components = [], array $data = [])
    {
        $this->urlBuilder = $url;
        parent::__construct($context, $uiComponentFactory, $components, $data);
    }

   public function prepareDataSource(array $dataSource)
   {
       if (isset($dataSource['data']['items'])) {
           foreach ($dataSource['data']['items'] as & $item) {
               // here we can also use the data from $item to configure some parameters of an action URL
               $item[$this->getData('name')] = [
                   'edit' => [
                       'href' => $this->urlBuilder->getUrl('magenest/movie/edit',['id'=> $item['movie_id']]),
                       'label' => __('Edit')
                   ],
                   'delete' => [
                       'href' => $this->urlBuilder->getUrl('magenest/movie/remove',['id'=> $item['movie_id']]),
                       'label' => __('delete')
                   ]
               ];
           }
       }
       return parent::prepareDataSource($dataSource); // TODO: Change the autogenerated stub
   }
}
