<?php
namespace Magenest\Movie\Ui\Component\Movie\Listing\Column;
use \Magento\Framework\View\Element\UiComponent\ContextInterface;
use \Magento\Framework\View\Element\UiComponentFactory;
use \Magento\Ui\Component\Listing\Columns\Column;
class Rating extends Column {

    public function __construct(ContextInterface $context, UiComponentFactory $uiComponentFactory, array $components = [], array $data = [])
    {
        parent::__construct($context, $uiComponentFactory, $components, $data);
    }

    public function prepareDataSource(array $dataSource)
    {
        if (isset($dataSource['data']['items'])) {
            foreach ($dataSource['data']['items'] as & $item) {
                $starHTML = '';
                for($i = 1; $i <= 5; $i++) {
                    if($item['rating'] >= $i){
                        $starHTML .= '<span style="color: yellow; font-size: 30px"> &#9733; </span>';
                    }else{
                        $starHTML .= '<span style="color: yellow;font-size: 30px"> &#9734; </span>';
                    }
                }
                $item['rating'] =  '<div style="width: max-content">'.$starHTML.'</div>';
            }
        }
        return parent::prepareDataSource($dataSource); // TODO: Change the autogenerated stub
    }
}