<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// phpcs:disable Magento2.Templates.ThisInTemplate.FoundThis

/**
 * Product view template
 *
 * @var $block \Magento\Catalog\Block\Product\View
 */
?>
<?php $_helper = $this->helper(Magento\Catalog\Helper\Output::class); ?>
<?php $_product = $block->getProduct(); ?>

<div class="product-add-form">
    <form data-product-sku="<?= $block->escapeHtml($_product->getSku()) ?>"
          action="<?= $block->escapeUrl($block->getSubmitUrl($_product)) ?>" method="post"
          id="product_addtocart_form"<?php if ($_product->getOptions()) : ?> enctype="multipart/form-data"<?php endif; ?>>
        <div class="field" style="margin-top: 8px; margin-bottom: 8px">
            <label for="name_receiver" class="label"><b>Name receiver</b></label>
            <div class="control" style="margin-top: 5px">
                <input type="text" id="name_receiver" name="name_receiver" style="width: auto" class="input-text ">

            </div>
        </div>
        <div class="field required">
            <label for="note" class="label"><b>Note</b></label>
            <div class="control" style="margin-top: 5px">
                <textarea name="note" id="note" data-validate="{'maxlength': 40}" class="textarea"></textarea>
            </div>
        </div>
        <input type="hidden" name="product" value="<?= (int)$_product->getId() ?>"/>
        <input type="hidden" name="selected_configurable_option" value=""/>
        <input type="hidden" name="related_product" id="related-products-field" value=""/>
        <input type="hidden" name="item" value="<?= (int)$block->getRequest()->getParam('id') ?>"/>
        <?= $block->getBlockHtml('formkey') ?>
        <?= $block->getChildHtml('form_top') ?>
        <?php if (!$block->hasOptions()) : ?>
            <?= $block->getChildHtml('product_info_form_content') ?>
        <?php else : ?>
            <?php if ($_product->isSaleable() && $block->getOptionsContainer() == 'container1') : ?>
                <?= $block->getChildChildHtml('options_container') ?>
            <?php endif; ?>
        <?php endif; ?>

        <?php if ($_product->isSaleable() && $block->hasOptions() && $block->getOptionsContainer() == 'container2') : ?>
            <?= $block->getChildChildHtml('options_container') ?>
        <?php endif; ?>
        <?= $block->getChildHtml('form_bottom') ?>
    </form>
</div>
<script>
    require([
        'jquery',
        'priceBox'
    ], function ($) {
        var dataPriceBoxSelector = '[data-role=priceBox]',
            dataProductIdSelector = '[data-product-id=<?= $block->escapeHtml($_product->getId()) ?>]',
            priceBoxes = $(dataPriceBoxSelector + dataProductIdSelector);

        priceBoxes = priceBoxes.filter(function (index, elem) {
            return !$(elem).find('.price-from').length;
        });

        priceBoxes.priceBox({'priceConfig': <?= /* @noEscape */ $block->getJsonConfig() ?>});


    });


</script>
