<?php
use Magento\Framework\App\ActionInterface;
/**
 * @var $block Magenest\DeliveryTime\Block\Sales
 */

$data = $block->getData('data');
$products = $block->getProductsCollection()->setCurPage($data['page'])->setPageSize(12);
$productBlock = $block->getLayout()->createBlock('Magento\Catalog\Block\Product\AbstractProduct');
$showAddTo = true;
$showCart = true;
?>

<div class="products wrapper grid products-grid">
    <ol class="products list items product-items">
        <?php foreach ($products as $_item):?>

            <li class="item product product-item">
                <div class="product-item-info ">
                    <a href="<?= $block->escapeUrl($block->getProductUrl($_item)) ?>"
                       class="product photo product-item-photo">
                        <?= $productBlock->getImage($_item, 'mini_cart_product_thumbnail')->toHtml() ?>
                    </a>
                    <div class="product details product-item-details">
                        <strong class="product name product-item-name"><a
                                class="product-item-link"
                                title="<?= $block->escapeHtmlAttr($_item->getName()) ?>"
                                href="<?= $block->escapeUrl($block->getProductUrl($_item)) ?>">
                                <?= $block->escapeHtml($_item->getName()) ?></a>
                        </strong>

                        <?= /* @noEscape */ $productBlock->getProductPrice($_item) ?>


                        <?php if ($showAddTo || $showCart):?>
                            <?php // phpcs:disable ?>
                            <div class="product actions product-item-actions">
                                <?php if ($showCart):?>
                                    <div class="actions-primary">
                                        <?php if ($_item->isSaleable()):?>
                                            <form data-role="tocart-form"
                                                  data-product-sku="<?= $block->escapeHtmlAttr($_item->getSku()) ?>"
                                                  action="<?= $block->escapeUrl($productBlock->getAddToCartUrl($_item)) ?>"
                                                  method="post">
                                                <input type="hidden" name="product"
                                                       value="<?= /* @noEscape */ (int)$_item->getEntityId() ?>">
                                                <input type="hidden"
                                                       name="<?= /* @noEscape */ ActionInterface::PARAM_NAME_URL_ENCODED?>"
                                                >
                                                <?= $block->getBlockHtml('formkey') ?>
                                                <button type="submit"
                                                        title="<?= $block->escapeHtmlAttr(__('Add to Cart')) ?>"
                                                        class="action tocart primary">
                                                    <span><?= $block->escapeHtml(__('Add to Cart')) ?></span>
                                                </button>
                                            </form>

                                        <?php else:?>
                                            <?php if ($_item->getIsSalable()):?>
                                                <div class="stock available">
                                                    <span><?= $block->escapeHtml(__('In stock')) ?></span>
                                                </div>
                                            <?php else:?>
                                                <div class="stock unavailable">
                                                    <span><?= $block->escapeHtml(__('Out of stock')) ?></span>
                                                </div>
                                            <?php endif; ?>
                                        <?php endif; ?>
                                    </div>
                                <?php endif; ?>

                                <?php if ($showAddTo):?>
                                    <div class="secondary-addto-links actions-secondary"
                                         data-role="add-to-links">
                                        <?php if ($addToBlock = $productBlock->getChildBlock('addto')):?>
                                            <?= $addToBlock->setProduct($_item)->getChildHtml() ?>
                                        <?php endif; ?>
                                    </div>
                                <?php endif; ?>
                            </div>
                            <?php // phpcs:enable ?>
                        <?php endif; ?>
                    </div>
                </div>
            </li>
        <?php endforeach ?>
    </ol>
</div>
