<?php
/**
 * @var $block Magenest\DeliveryTime\Block\Sales
 */

$productBlock = $block->getLayout()->createBlock('Magento\Catalog\Block\Product\AbstractProduct');
$pages = $block->getPages();
?>
<style>
    .pagination {
        display: inline-block;
    }

    .pagination a {
        color: black;
        float: left;
        padding: 8px 16px;
        text-decoration: none;
    }

    .pagination a.active {
        background-color: #4CAF50;
        color: white;
    }

    .pagination a:hover:not(.active) {background-color: #ddd;}
</style>
<div style="float:right">
    <button id="button">
        <span><?= $block->escapeHtml(__('SALE')) ?></span>
    </button>
</div>
<div id="modal" style="display: none">
    <div class="modal-body-content" id="list-products-sale">

    </div>

    <div class="order-products-toolbar toolbar bottom">
        <div class="pagination">
            <a href="#" onclick="prevPage()">&laquo;</a>
            <?php foreach ($pages as $page) : ?>
                <a class="pagination-page pagination-page-<?= $page ?>" onclick="getPagination(<?= $page ?>)" href="#"><?= $page ?></a>
            <?php endforeach;?>
            <a href="#" onclick="nextPage()">&raquo;</a>
        </div>
        <input type="hidden" name="current_page" id="current_page" value="" />
    </div>
    <div id="loader-pagination" data-mage-init='{"loader": { "icon": "<?=$block->getViewFileUrl('images/loader-2.gif')?>" }}'>
    </div>
</div>
<script type="text/javascript">
    require([
        "jquery",
        "Magento_Ui/js/modal/modal"
    ],function($, modal) {

        $(document).ready(function() {
            var options = {
                type: 'popup',
                responsive: true,
                title: $.mage.__('Sales products'),
                buttons: []
            };
            var popup = modal(options, $('#modal'));
            $("#button").click(function() {
                $('#modal').modal('openModal');
            });
            getPagination(1);
        });

    });

    function getPagination(page) {
        require(['jquery', 'loader'], function($) {
            var url = "<?php echo $productBlock->getUrl().'delivery/ajax/sale'?>";
            $('#loader-pagination').trigger('processStart');
            $.ajax({
                url: url,
                type: 'GET',
                dataType: 'json',
                data: {
                    page: page
                },
                complete: function(response) {
                    $('.pagination-page').removeClass('active');
                    $('.pagination-page-'+ response.responseJSON.page).addClass('active');
                    $('#current_page').val(response.responseJSON.page);
                    $('#list-products-sale').html(response.responseJSON.output)
                    $('#loader-pagination').trigger('processStop');
                },
                error: function (xhr, status, errorThrown) {
                    console.log('Error happens. Try again.');
                }
            });
        });
    }
    function prevPage() {
        require(['jquery'],function($) {
            let currentPage =  parseInt($('#current_page').val());
            console.log(currentPage)
            if (currentPage > 1) {
                getPagination(currentPage - 1);
            }
        });
    }
    function nextPage() {
        require(['jquery'],function($) {
            let currentPage = parseInt($('#current_page').val());
            let totalPages = <?= count($pages); ?>;
            console.log(totalPages)
            console.log(currentPage)
            if (currentPage < totalPages) {
                getPagination(currentPage + 1);
            }
        });
    }
</script>