<div style="<?php if ($block->getNameManufacturer() == '') echo 'display:none' ?>">Manufacturer:
    <b style="color:blue; cursor: pointer" id="manufacturer"><?php echo $block->getNameManufacturer() ?></b>
</div>
<script>
    require([
        'jquery'
    ], function ($) {
        $('#manufacturer').click(() => {
            alert('<?php echo $block->showInfoManufacturer() ?> ');
        });
    })
</script>