<form class="form contact"
      action="create"
      id="signin-form"
      method="post"
      data-hasrequired="<?= $block->escapeHtmlAttr(__('* Required Fields')) ?>"
      data-mage-init='{"validation":{}}'>
    <fieldset class="fieldset">
        <legend class="legend"><span><?= $block->escapeHtml(__('Sign-in Infomation')) ?></span></legend>
        <br/>
        <div class="field email required">
            <label class="label" for="email"><span><?= $block->escapeHtml(__('Email')) ?></span></label>
            <div class="control">
                <input name="email" id="email" title="<?= $block->escapeHtmlAttr(__('Email')) ?>"
                       value=""
                       class="input-text" type="email" data-validate="{required:true, 'validate-email':true}"/>
            </div>
        </div>

        <div class="field password required">
            <label class="label" for="password"><span><?= $block->escapeHtml(__('Password')) ?></span></label>
            <div class="control">
                <input name="password" id="password" title="<?= $block->escapeHtmlAttr(__('Password')) ?>"
                       value=""
                       class="input-password validate-new-password required-entry" type="password"/>
            </div>
        </div>
        <div class="field confirm-password required">
            <label class="label"
                   for="confirm-password"><span><?= $block->escapeHtml(__('Confirm Password')) ?></span></label>
            <div class="control">
                <input name="confirmPassword" id="confirm-password"
                       title="<?= $block->escapeHtmlAttr(__('Passwoed')) ?>"
                       value=""
                       class="input-password required-entry validate-cpassword" type="password"/>
            </div>
        </div>
    </fieldset>
    <div class="actions-toolbar">
        <div class="primary">
            <input type="hidden" name="hideit" id="hideit" value=""/>
            <button type="submit" title="<?= $block->escapeHtmlAttr(__('Create Account')) ?>"
                    class="action submit primary">
                <span><?= $block->escapeHtml(__('Create Account')) ?></span>
            </button>
        </div>
    </div>
</form>
<script type="text/javascript"
//<![CDATA[
var dataForm = new VarienForm('person-form-validate', true);
//]]>
</script>
