<?php
namespace Learning\FirstUnit\Model;

class Subscription extends \Magento\Framework\Model\AbstractModel{
    const STATUS_PENDING = 'pending';
    const STATUS_APPROVED = 'approved';
    const STATUS_DECLINED = 'declined';

    protected function _construct()
    {
        $this->_init('Learning\FirstUnit\Model\ResourceModel\Subscription');
    }
    public function load($modelId, $field = null)
    {
        return parent::load($modelId, $field); // TODO: Change the autogenerated stub
    }

}