<?php
 namespace magenest\Movie\Model;

 class MovieActors extends \Magento\Framework\Model\AbstractModel {

     protected function _construct()
     {
         $this->_init('Magenest\Movie\Model\ResourceModel\MovieActors');
         parent::_construct(); // TODO: Change the autogenerated stub
     }
 }