<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var $block \Magento\Catalog\Block\Product\View */
?>
<?php $_product = $block->getProduct(); ?>
<?php $buttonTitle = __('Add to Cart'); ?>
<?php if ($_product->isSaleable()) :?>
    <div class="box-tocart">
        <div class="fieldset">
            <?php if ($block->shouldRenderQuantity()) :?>
                <div class="field qty">
                    <label class="label" for="qty"><span><?= $block->escapeHtml(__('Qty')) ?></span></label>
                    <div class="control">
                        <button class="btn-qty minus" >
                            <span><?= $block->escapeHtml(__('Desc')) ?></span>
                        </button>
                        <input type="number"
                               name="qty"
                               id="qty"
                               min="0"
                               value="<?= $block->getProductDefaultQty() * 1 ?>"
                               title="<?= $block->escapeHtmlAttr(__('Qty')) ?>"
                               class="input-text qty"
                               data-validate="<?= $block->escapeHtml(json_encode($block->getQuantityValidators())) ?>"
                        />
                        <button class="btn-qty plus" >
                            <span><?= $block->escapeHtml(__('Incre')) ?></span>
                        </button>
                    </div>
                </div>
            <?php endif; ?>
            <div class="actions">
                <button type="submit"
                        title="<?= $block->escapeHtmlAttr($buttonTitle) ?>"
                        class="action primary tocart"
                        id="product-addtocart-button" disabled>
                    <span><?= $block->escapeHtml($buttonTitle) ?></span>
                </button>
                <?= $block->getChildHtml('', true) ?>
            </div>
        </div>
    </div>
<?php endif; ?>
<script type="text/x-magento-init">
    {
        "#product_addtocart_form": {
            "Magento_Catalog/js/validate-product": {}
        }
    }
</script>
<script type="text/javascript">
    require(['jquery','domReady!'],function($){
        var dataValidate = $('#qty').data('validate');
        var qtyIncrements = 1;
        if(dataValidate["validate-item-quantity"]["qtyIncrements"] != null){
            qtyIncrements = dataValidate["validate-item-quantity"]["qtyIncrements"]
        }
        $(".btn-qty").click(function (event) {
            var $button = $(this);
            var oldValue = $button.closest('.control').find("input#qty").val();
            var defaultValue = <?php /* @escapeNotVerified */ echo $block->getProductDefaultQty() * 1 ?>;
            if ($button.hasClass('plus')) {
                var newVal = parseFloat(oldValue) + qtyIncrements;
            } else {
                if (oldValue > defaultValue) {
                    var newVal = parseFloat(oldValue) - qtyIncrements;
                } else {
                    newVal = defaultValue;
                }
            }
            $button.closest('.control').find("input#qty").val(newVal);
            event.preventDefault();
        });

    });
</script>
