<?php

namespace Magenest\Movie\Model\ResourceModel\MovieActors;

use  Magento\Framework\Model\ResourceModel\Db\Collection\AbstractCollection;

class Collection extends AbstractCollection {

    protected function _construct()
    {
        $this->_init('Magenest\Movie\Model\MovieActors', 'Magenest\Movie\Model\ResourceModel\MovieActors');
        parent::_construct(); // TODO: Change the autogenerated stub
    }
}