<?php
namespace Learning\FirstUnit\Console\Command;

use Symfony\Component\Console\Command\Command;
use Symfony\Component\Console\Input\InputInterface;
use Symfony\Component\Console\Output\OutputInterface;
use Symfony\Component\Console\Input\InputOption;

class HelloWorldCommand extends Command {
const INPUT_KEY_EXTENDED = "extended";
const INPUT_KEY_TEST = 'test';
    protected function configure()
    {
        $option = [
                new InputOption(
                    self::INPUT_KEY_EXTENDED,
                    null,
                    inputOption::VALUE_NONE,
                    'Get extended info'
                ),
            new InputOption(
                self:: INPUT_KEY_TEST,
                null,
                inputOption::VALUE_NONE,
                'test command'
            )
        ];
        $this->setName("helloworld:info")
            ->setDescription("Get in about intallation")
            ->setDefinition($option);


        parent::configure(); // TODO: Change the autogenerated stub
    }

    protected function execute(InputInterface $input, OutputInterface $output)
    {
        $output->writeln('<error>'.' writeln surrounded by tag error'.'</error>');
        $output->writeln('<comment>'.'writeln surrounded by tag comment'.'</comment>');
        $output->writeln('<info>'.'writeln surrounded by tag info'.'</info>');
        $output->writeln('<question>'.'writeln surrounded by tag question'.'</question>');
        $output->writeln('writeln normal output');
        if ($input->getOption(self::INPUT_KEY_EXTENDED)) {
            $output->writeln('');
            $output->writeln('<info>'.'Extended parameter is given'.'</info>');
        }
        if($input->getOption(self::INPUT_KEY_TEST)) {
            $output->writeln('');
            $output->writeln('test success !');
        }
        $output->writeln('');
    }
}