<?php
namespace Learning\FirstUnit\Block;

use Magento\Framework\View\Element\Template;

class Landingspage extends Template{
    public function getLandingsUrl()
    {
        return $this->getUrl("test");
    }
    public function getRedirectUrl() {
        return $this->getUrl("helloworld/index/redirect");
    }
    public function getModuleName()
    {
        return parent::getModuleName(); // TODO: Change the autogenerated stub
    }
}
