<?php

namespace Learning\FirstUnit\Ui\Component\Listing\Column;
use Magento\Framework\UrlInterface;
use Magento\Framework\View\Element\UiComponent\ContextInterface;
use Magento\Framework\View\Element\UiComponentFactory;
use Magento\Ui\Component\Listing\Columns\Column;



class Actions extends  Column{

    /**
     * @var UrlInterface
     */
    private $urlBuilder;

    public function __construct(ContextInterface $context, UiComponentFactory $uiComponentFactory, UrlInterface $url, array $components = [], array $data = [])
{
    $this->urlBuilder = $url;
    parent::__construct($context, $uiComponentFactory, $components, $data);
}

    public function prepareDataSource(array $dataSource)
    {
        if (isset($dataSource['data']['items'])) {
            foreach ($dataSource['data']['items'] as & $item) {
                // here we can also use the data from $item to configure some parameters of an action URL
                $item[$this->getData('name')] = [
                    'edit' => [
                        'href' => $this->urlBuilder->getUrl("helloworld/subscription/edit",["id"=>$item['subscription_id']]),
                        'label' => __('Edit')
                    ],
                    'delete' => [
                        'href' => $this->urlBuilder->getUrl('helloworld/subscription/delete',  ['id'=>$item['subscription_id']]),
                        'label' => __('delete')
                    ]
                ];
            }
        }
        return parent::prepareDataSource($dataSource); // TODO: Change the autogenerated stub
    }
}